apiVersion: v1
kind: Pod
metadata:
  name: update-checker
spec:
  containers:
    - name: update-checker
      image: joont92/update-checker:latest
      command:
        - sh
        - -c
        - |
          while true
          do
            echo "[`date`] `curl -s http://test-service`"
            sleep 1
          done
